#!/usr/bin/env python3
"""
Plot model-minus-observation error maps for CM2 atmosphere/ocean output.

The script supports observation files generated by
data_preprocess/preprocess_observation.py, whose default output is:
    /data/ouc/zhuxianrui/CM2-f2py/out_nc_observation/merged_observation.pt

For speed, the default model time selection uses the nearest model time slice.
Use --time-method interp to reproduce linear time interpolation.
"""

from __future__ import annotations

import argparse
import ast
import logging
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
import xarray as xr


OBS_FILE_DEFAULT = "/data/ouc/zhuxianrui/CM2-f2py/out_nc_observation/merged_observation.pt"
WORK_DIRS_DEFAULT = {
    "ctl": "/data/assim-f2py-test/work_ctl/cm2_ctl",
    "scda": "/data/assim-f2py-test/work_ctl/cm2_scda_final7",
    "wcda": "/data/assim-f2py-test/work_ctl/cm2_wcda",
}

FILES = {"atm": "atmos_3hourly.nc", "ocn": "ocean_3hourly.nc"}
TIME_CANDIDATES = ["time", "TIME", "Time", "time_counter", "t", "L", "T", "valid_time"]

OBS_VARS = {"ps": "ps1", "sst": "sst"}
MODEL_VARS = {"ps": ("atm", "ps"), "sst": ("ocn", "sst")}

ATM_SHAPE = (90, 144)
OCN_SHAPE = (200, 360)


def setup_logging(logfile_path: str) -> None:
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(fmt)
    file_handler = logging.FileHandler(logfile_path)
    file_handler.setFormatter(fmt)

    logger.addHandler(stream_handler)
    logger.addHandler(file_handler)


def detect_time_coord(ds: xr.Dataset | xr.DataArray) -> str:
    for name in TIME_CANDIDATES:
        if name in ds.coords or name in ds.variables:
            return name
    for name in ds.dims:
        if name.lower() == "time":
            return name
    raise ValueError("Could not find a time coordinate.")


def get_times_from_ds(ds: xr.Dataset) -> tuple[pd.DatetimeIndex, str]:
    time_name = detect_time_coord(ds)
    values = ds[time_name].values
    try:
        times = pd.DatetimeIndex(pd.to_datetime(values))
    except Exception:
        times = pd.DatetimeIndex(pd.to_datetime(values.astype("datetime64[ns]")))
    return times, time_name


def to_pd_timestamp_safe(value) -> pd.Timestamp:
    if isinstance(value, pd.Timestamp):
        return value
    try:
        return pd.to_datetime(value)
    except Exception:
        pass

    try:
        return pd.Timestamp(
            year=int(getattr(value, "year")),
            month=int(getattr(value, "month", 1)),
            day=int(getattr(value, "day", 1)),
            hour=int(getattr(value, "hour", 0)),
            minute=int(getattr(value, "minute", 0)),
            second=int(getattr(value, "second", 0)),
        )
    except Exception:
        return pd.to_datetime(str(value))


def convert_target_times_to_model_type(target_times: pd.DatetimeIndex, model_time_values: np.ndarray) -> np.ndarray:
    flat = np.ravel(model_time_values)
    if len(flat) == 0:
        raise ValueError("Model time array is empty.")

    sample = flat[0]
    if isinstance(sample, np.datetime64) or np.issubdtype(type(sample), np.datetime64) or isinstance(sample, pd.Timestamp):
        return target_times.values.astype("datetime64[ns]")

    cls = type(sample)
    converted = []
    for ts in pd.DatetimeIndex(target_times):
        try:
            converted.append(cls(int(ts.year), int(ts.month), int(ts.day), int(ts.hour), int(ts.minute), int(ts.second)))
        except TypeError:
            converted.append(cls(int(ts.year), int(ts.month), int(ts.day)))
    return np.array(converted, dtype=object)


def to_numpy_array(value) -> np.ndarray:
    if hasattr(value, "detach"):
        return value.detach().cpu().numpy()
    return np.asarray(value)


def as_time_yx(value, expected_shape: tuple[int, int], ntime: int, var_name: str) -> np.ndarray:
    arr = np.asarray(to_numpy_array(value), dtype=np.float32)
    arr = np.squeeze(arr)

    if arr.ndim == 2:
        arr = arr[None, :, :]

    if arr.ndim > 3:
        time_axes = [axis for axis, size in enumerate(arr.shape) if size == ntime]
        if time_axes:
            arr = np.moveaxis(arr, time_axes[0], 0)
        while arr.ndim > 3:
            singleton_axes = [axis for axis in range(1, arr.ndim) if arr.shape[axis] == 1]
            if singleton_axes:
                arr = np.squeeze(arr, axis=singleton_axes[0])
            else:
                arr = np.take(arr, 0, axis=1)

    if arr.ndim != 3:
        raise ValueError(f"{var_name} observation must be 2D or 3D after squeezing, got {arr.shape}.")

    if arr.shape[0] != ntime:
        time_axes = [axis for axis, size in enumerate(arr.shape) if size == ntime]
        if time_axes:
            arr = np.moveaxis(arr, time_axes[0], 0)

    if arr.shape[0] != ntime:
        raise ValueError(f"{var_name} observation time length mismatch: data={arr.shape[0]}, time={ntime}.")
    if arr.shape[1:] == expected_shape:
        return arr
    if arr.shape[1:] == (expected_shape[1], expected_shape[0]):
        return arr.transpose(0, 2, 1)

    raise ValueError(f"{var_name} observation spatial shape {arr.shape[1:]} does not match {expected_shape}.")


def load_pt_observations(obs_file: str) -> xr.Dataset:
    try:
        import torch
    except ImportError as exc:
        raise ImportError("Reading .pt observations requires PyTorch.") from exc

    payload = torch.load(obs_file, map_location="cpu", weights_only=False)
    data = payload.get("data", payload)
    coords = payload.get("coords", {})
    raw_times = coords.get("time", payload.get("time", None))
    if raw_times is None:
        raise ValueError("Observation .pt file does not contain coords['time'].")

    obs_times = pd.DatetimeIndex(pd.to_datetime(np.asarray(raw_times)))
    ntime = len(obs_times)
    ps_key = OBS_VARS["ps"]
    sst_key = OBS_VARS["sst"]

    if ps_key not in data or sst_key not in data:
        raise KeyError(f"Observation .pt data must contain {ps_key!r} and {sst_key!r}; available keys: {list(data.keys())}")

    ps = as_time_yx(data[ps_key], ATM_SHAPE, ntime, ps_key)
    sst = as_time_yx(data[sst_key], OCN_SHAPE, ntime, sst_key)

    coords_out = {
        "time": obs_times,
        "lat_atm": np.arange(ATM_SHAPE[0], dtype=float),
        "lon_atm": np.arange(ATM_SHAPE[1], dtype=float),
        "lat_ocn": np.arange(OCN_SHAPE[0], dtype=float),
        "lon_ocn": np.arange(OCN_SHAPE[1], dtype=float),
    }

    return xr.Dataset(
        {
            ps_key: xr.DataArray(
                ps,
                dims=("time", "lat_atm", "lon_atm"),
                coords={key: coords_out[key] for key in ("time", "lat_atm", "lon_atm")},
            ),
            sst_key: xr.DataArray(
                sst,
                dims=("time", "lat_ocn", "lon_ocn"),
                coords={key: coords_out[key] for key in ("time", "lat_ocn", "lon_ocn")},
            ),
        },
        coords=coords_out,
    )


def load_observation_dataset(obs_file: str) -> xr.Dataset:
    if str(obs_file).lower().endswith(".pt"):
        return load_pt_observations(obs_file)
    return xr.open_dataset(obs_file, decode_times=True)


def centers_to_edges(centers: np.ndarray) -> np.ndarray:
    centers = np.asarray(centers, dtype=float)
    if centers.size == 1:
        return np.array([centers[0] - 0.5, centers[0] + 0.5])

    edges = np.empty(centers.size + 1, dtype=float)
    edges[1:-1] = 0.5 * (centers[:-1] + centers[1:])
    edges[0] = centers[0] - 0.5 * (centers[1] - centers[0])
    edges[-1] = centers[-1] + 0.5 * (centers[-1] - centers[-2])
    return edges


def find_coord(ds: xr.Dataset, preferred_names: list[str], kind: str) -> str:
    for name in preferred_names:
        if name in ds.coords:
            return name

    token = "lat" if kind == "lat" else "lon"
    for name in ds.coords:
        if token in name.lower():
            return name

    raise RuntimeError(f"Could not find {kind} coordinates.")


def nearest_time_indices(model_time_values: np.ndarray, target_times: pd.DatetimeIndex) -> np.ndarray:
    model_times = pd.DatetimeIndex([to_pd_timestamp_safe(value) for value in np.ravel(model_time_values)])
    indices = model_times.get_indexer(target_times, method="nearest")
    if np.any(indices < 0):
        raise ValueError("Failed to find nearest model times for all target times.")
    return indices.astype(int)


def select_interp_snapshot(da: xr.DataArray, time_coord: str, target_time: pd.Timestamp) -> xr.DataArray:
    converted = convert_target_times_to_model_type(pd.DatetimeIndex([target_time]), da[time_coord].values)
    return da.interp({time_coord: converted}).isel({time_coord: 0}).squeeze(drop=True)


def drop_to_2d(da: xr.DataArray) -> np.ndarray:
    reduced = da.squeeze(drop=True)
    while reduced.ndim > 2:
        reduced = reduced.isel({reduced.dims[0]: 0})
    return np.asarray(reduced.values)


def map_model_to_obs_grid(
    da: xr.DataArray,
    expected_shape: tuple[int, int],
    obs_lat_name: str,
    obs_lon_name: str,
    obs_lats: np.ndarray,
    obs_lons: np.ndarray,
) -> xr.DataArray:
    data = drop_to_2d(da)
    if data.ndim != 2:
        raise ValueError(f"Model snapshot is not 2D after squeezing; got {data.shape}.")

    if data.shape == expected_shape:
        mapped = data
    elif data.shape == (expected_shape[1], expected_shape[0]):
        mapped = data.T
    else:
        raise ValueError(f"Model shape {data.shape} does not match expected observation shape {expected_shape}.")

    return xr.DataArray(
        mapped,
        dims=(obs_lat_name, obs_lon_name),
        coords={obs_lat_name: obs_lats, obs_lon_name: obs_lons},
    )


def compute_error(model_da: xr.DataArray, obs_da: xr.DataArray) -> tuple[xr.DataArray, float]:
    err = model_da - obs_da
    values = np.asarray(err.values, dtype=float)
    rmse = float(np.sqrt(np.nanmean(np.square(values))))
    return err.squeeze(drop=True), rmse


def finite_absmax(da: xr.DataArray) -> float:
    values = np.asarray(da.values, dtype=float)
    if not np.any(np.isfinite(values)):
        return 0.0
    return float(np.nanmax(np.abs(values)))


def parse_workdirs(value) -> dict[str, str]:
    if isinstance(value, dict):
        return value
    try:
        parsed = ast.literal_eval(value)
    except Exception as exc:
        raise ValueError("workdirs must be a Python dict literal.") from exc
    if not isinstance(parsed, dict):
        raise ValueError("workdirs must be a Python dict literal.")
    return parsed


def open_model_datasets(work_dirs: dict[str, str]) -> dict[str, dict[str, object]]:
    case_datasets = {}
    for case, work_dir in work_dirs.items():
        logging.info("Opening case=%s from %s", case, work_dir)
        atm_path = os.path.join(work_dir, FILES["atm"])
        ocn_path = os.path.join(work_dir, FILES["ocn"])
        if not os.path.exists(atm_path) or not os.path.exists(ocn_path):
            raise FileNotFoundError(f"Missing model files for {case}: {atm_path} or {ocn_path}")

        ds_atm = xr.open_dataset(atm_path, decode_times=True)
        ds_ocn = xr.open_dataset(ocn_path, decode_times=True)
        atm_time_coord = detect_time_coord(ds_atm)
        ocn_time_coord = detect_time_coord(ds_ocn)

        ps_name = MODEL_VARS["ps"][1]
        sst_name = MODEL_VARS["sst"][1]
        if ps_name not in ds_atm:
            raise KeyError(f"{case} atmosphere file is missing {ps_name!r}.")
        if sst_name not in ds_ocn:
            raise KeyError(f"{case} ocean file is missing {sst_name!r}.")

        atm_times = ds_atm[atm_time_coord].values
        ocn_times = ds_ocn[ocn_time_coord].values
        start_case = max(to_pd_timestamp_safe(np.ravel(atm_times)[0]), to_pd_timestamp_safe(np.ravel(ocn_times)[0]))
        end_case = min(to_pd_timestamp_safe(np.ravel(atm_times)[-1]), to_pd_timestamp_safe(np.ravel(ocn_times)[-1]))
        logging.info("%s coverage: %s to %s", case, start_case, end_case)

        case_datasets[case] = {
            "atm": ds_atm,
            "ocn": ds_ocn,
            "atm_time_coord": atm_time_coord,
            "ocn_time_coord": ocn_time_coord,
            "time_range": (start_case, end_case),
        }

    return case_datasets


def draw_error_maps(
    outdir: str,
    frame_index: int,
    frame_time: pd.Timestamp,
    row_order: list[str],
    col_order: list[str],
    err_dict: dict[tuple[str, str], xr.DataArray],
    rmse_this_time: dict[str, dict[str, float]],
    absmax_by_var: dict[str, float],
    obs_axes: dict[str, tuple[np.ndarray, np.ndarray]],
    figsize: tuple[float, float],
) -> str:
    fig, axes = plt.subplots(nrows=len(row_order), ncols=len(col_order), figsize=figsize, constrained_layout=True)
    axes = np.atleast_2d(axes)
    col_meshes = [None] * len(col_order)

    for i_row, case in enumerate(row_order):
        for j_col, var in enumerate(col_order):
            ax = axes[i_row, j_col]
            data = drop_to_2d(err_dict[(case, var)])
            lat, lon = obs_axes[var]
            vabs = absmax_by_var[var]
            vmin, vmax = (-1e-8, 1e-8) if not np.isfinite(vabs) or vabs == 0.0 else (-vabs, vabs)

            try:
                lon_edges, lat_edges = np.meshgrid(centers_to_edges(lon), centers_to_edges(lat))
                mesh = ax.pcolormesh(lon_edges, lat_edges, data, shading="auto", vmin=vmin, vmax=vmax, cmap="RdBu_r")
            except Exception as exc:
                logging.warning("pcolormesh failed for case=%s var=%s: %s; using imshow", case, var, exc)
                mesh = ax.imshow(data, origin="lower", aspect="auto", vmin=vmin, vmax=vmax, cmap="RdBu_r")

            ax.set_xlabel("x")
            ax.set_ylabel("y")
            ax.set_title("%s - %s (rmse=%.4e)" % (case, var.upper(), rmse_this_time[var][case]))
            if col_meshes[j_col] is None:
                col_meshes[j_col] = mesh

    for j_col, mesh in enumerate(col_meshes):
        if mesh is None:
            continue
        cbar = fig.colorbar(mesh, ax=axes[:, j_col], orientation="vertical", fraction=0.03, pad=0.02)
        cbar.set_label("error", fontsize=9)
        cbar.ax.yaxis.set_major_locator(mticker.MaxNLocator(nbins=6))
        cbar.formatter = mticker.ScalarFormatter(useMathText=True)
        cbar.formatter.set_powerlimits((-3, 4))
        cbar.update_ticks()
        cbar.ax.tick_params(labelsize=8)

    fig.suptitle("Error maps (model - obs) at %s" % pd.to_datetime(frame_time), fontsize=14)
    outpath = os.path.join(outdir, "error_map_%03d_%s.png" % (frame_index + 1, pd.to_datetime(frame_time).strftime("%Y%m%dT%H%M")))
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    fig.savefig(outpath, dpi=150)
    plt.close(fig)
    return outpath


def draw_rmse_series(
    outdir: str,
    times: pd.DatetimeIndex,
    row_order: list[str],
    rmse_store: dict[str, dict[str, list[float]]],
    figsize: tuple[float, float],
) -> str:
    fig, axes = plt.subplots(nrows=2, ncols=1, figsize=figsize, constrained_layout=True)
    for index, var in enumerate(["sst", "ps"]):
        ax = axes[index]
        for case in row_order:
            ax.plot(times, rmse_store[var][case], label=case)
        ax.set_title("RMSE over time for %s" % var.upper())
        ax.set_xlabel("time")
        ax.set_ylabel("rmse")
        ax.legend()

    outpath = os.path.join(outdir, "rmse_time_series.png")
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    fig.savefig(outpath, dpi=150)
    plt.close(fig)
    return outpath


def log_rmse_summary(rmse_store: dict[str, dict[str, list[float]]], row_order: list[str]) -> None:
    logging.info("RMSE mean summary over all selected frames:")
    for var in ["ps", "sst"]:
        for case in row_order:
            values = np.asarray(rmse_store[var][case], dtype=float)
            mean_value = float(np.nanmean(values)) if values.size else float("nan")
            logging.info("RMSE mean %s %s: %.6e (n=%d)", var.upper(), case, mean_value, values.size)


def main(args: argparse.Namespace) -> None:
    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)
    setup_logging(os.path.join(outdir, "error_map_generation.log"))

    obs_file = args.obs
    work_dirs = parse_workdirs(args.workdirs)
    logging.info("Output directory: %s", outdir)
    logging.info("Observation file: %s", obs_file)
    logging.info("Model work directories: %s", work_dirs)
    logging.info("Model time selection method: %s", args.time_method)

    obs_ds = load_observation_dataset(obs_file)
    obs_times, obs_time_coord = get_times_from_ds(obs_ds)
    logging.info("Observation time coordinate: %s; records: %d", obs_time_coord, len(obs_times))

    obs_atm_lat_name = "lat_atm" if "lat_atm" in obs_ds.coords else find_coord(obs_ds, ["lat_atm", "lat"], "lat")
    obs_atm_lon_name = "lon_atm" if "lon_atm" in obs_ds.coords else find_coord(obs_ds, ["lon_atm", "lon"], "lon")
    obs_ocn_lat_name = "lat_ocn" if "lat_ocn" in obs_ds.coords else find_coord(obs_ds, ["lat_ocn", "lat"], "lat")
    obs_ocn_lon_name = "lon_ocn" if "lon_ocn" in obs_ds.coords else find_coord(obs_ds, ["lon_ocn", "lon"], "lon")

    obs_vars = {
        "ps": obs_ds[OBS_VARS["ps"]].squeeze(drop=True),
        "sst": obs_ds[OBS_VARS["sst"]].squeeze(drop=True),
    }
    obs_atm_lats = np.squeeze(obs_ds[obs_atm_lat_name].values)
    obs_atm_lons = np.squeeze(obs_ds[obs_atm_lon_name].values)
    obs_ocn_lats = np.squeeze(obs_ds[obs_ocn_lat_name].values)
    obs_ocn_lons = np.squeeze(obs_ds[obs_ocn_lon_name].values)
    logging.info("Observation atm grid: %d x %d", obs_atm_lats.size, obs_atm_lons.size)
    logging.info("Observation ocn grid: %d x %d", obs_ocn_lats.size, obs_ocn_lons.size)

    case_datasets = open_model_datasets(work_dirs)
    global_start = max(info["time_range"][0] for info in case_datasets.values())
    global_end = min(info["time_range"][1] for info in case_datasets.values())
    common_times = obs_times[(obs_times >= global_start) & (obs_times <= global_end)]
    if args.max_frames is not None:
        common_times = common_times[: args.max_frames]
    if len(common_times) == 0:
        raise RuntimeError("No common observation/model times found.")
    logging.info("Common time range: %s to %s; frames: %d", common_times[0], common_times[-1], len(common_times))

    if args.time_method == "nearest":
        for info in case_datasets.values():
            info["atm_indices"] = nearest_time_indices(info["atm"][info["atm_time_coord"]].values, common_times)
            info["ocn_indices"] = nearest_time_indices(info["ocn"][info["ocn_time_coord"]].values, common_times)

    row_order = [case for case in ["ctl", "wcda", "scda"] if case in case_datasets]
    row_order.extend(case for case in case_datasets if case not in row_order)
    col_order = ["ps", "sst"]
    rmse_store = {var: {case: [] for case in row_order} for var in col_order}

    per_w = float(args.subplot_width)
    per_h = per_w * 9.0 / 16.0
    map_figsize = (2 * per_w, max(1, len(row_order)) * per_h)
    series_figsize = (2 * per_w, 2 * per_h)
    obs_axes = {"ps": (obs_atm_lats, obs_atm_lons), "sst": (obs_ocn_lats, obs_ocn_lons)}

    for idx, frame_time in enumerate(common_times):
        logging.info("Processing frame %d/%d: %s", idx + 1, len(common_times), frame_time)
        obs_ps_snap = obs_vars["ps"].sel({obs_time_coord: frame_time}).squeeze(drop=True)
        obs_sst_snap = obs_vars["sst"].sel({obs_time_coord: frame_time}).squeeze(drop=True)

        err_dict = {}
        rmse_this_time = {"ps": {}, "sst": {}}
        absmax_by_var = {"ps": 0.0, "sst": 0.0}

        for case in row_order:
            info = case_datasets[case]
            model_ps = info["atm"][MODEL_VARS["ps"][1]]
            model_sst = info["ocn"][MODEL_VARS["sst"][1]]

            if args.time_method == "nearest":
                model_ps_snap = model_ps.isel({info["atm_time_coord"]: int(info["atm_indices"][idx])}).squeeze(drop=True)
                model_sst_snap = model_sst.isel({info["ocn_time_coord"]: int(info["ocn_indices"][idx])}).squeeze(drop=True)
            else:
                model_ps_snap = select_interp_snapshot(model_ps, info["atm_time_coord"], frame_time)
                model_sst_snap = select_interp_snapshot(model_sst, info["ocn_time_coord"], frame_time)

            mapped_ps = map_model_to_obs_grid(model_ps_snap, ATM_SHAPE, obs_atm_lat_name, obs_atm_lon_name, obs_atm_lats, obs_atm_lons)
            mapped_sst = map_model_to_obs_grid(model_sst_snap, OCN_SHAPE, obs_ocn_lat_name, obs_ocn_lon_name, obs_ocn_lats, obs_ocn_lons)

            err_ps, rmse_ps = compute_error(mapped_ps, obs_ps_snap)
            err_sst, rmse_sst = compute_error(mapped_sst, obs_sst_snap)

            err_dict[(case, "ps")] = err_ps
            err_dict[(case, "sst")] = err_sst
            rmse_this_time["ps"][case] = rmse_ps
            rmse_this_time["sst"][case] = rmse_sst
            rmse_store["ps"][case].append(rmse_ps)
            rmse_store["sst"][case].append(rmse_sst)
            absmax_by_var["ps"] = max(absmax_by_var["ps"], finite_absmax(err_ps))
            absmax_by_var["sst"] = max(absmax_by_var["sst"], finite_absmax(err_sst))

        outpath = draw_error_maps(
            outdir,
            idx,
            frame_time,
            row_order,
            col_order,
            err_dict,
            rmse_this_time,
            absmax_by_var,
            obs_axes,
            map_figsize,
        )
        logging.info("Saved %s", outpath)

    log_rmse_summary(rmse_store, row_order)

    rmse_path = draw_rmse_series(outdir, common_times, row_order, rmse_store, series_figsize)
    logging.info("Saved %s", rmse_path)
    logging.info("All done. Generated %d error-map frames.", len(common_times))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--obs", type=str, default=OBS_FILE_DEFAULT)
    parser.add_argument("--workdirs", type=str, default=WORK_DIRS_DEFAULT)
    parser.add_argument("--outdir", type=str, default="./output_images")
    parser.add_argument("--max-frames", type=int, default=None, help="Only process the first N frames for debugging.")
    parser.add_argument("--subplot-width", type=float, default=8.0, help="Width of each subplot in inches.")
    parser.add_argument(
        "--time-method",
        choices=("nearest", "interp"),
        default="nearest",
        help="nearest is faster; interp uses linear time interpolation.",
    )
    main(parser.parse_args())
