
function ens_all_var(domains)
%% 路径设置 —— 根据实际情况自行修改
srcfile = sprintf('/public2/wrf_teach/ens_read_write/wrfinput_%s', domains);
dstfile = '../wrfinput_d01'; %不同domain都是一个文件名，因为内层采用了nodwn的方式运行

%% 变量列表（直接内置，不再读取 var.txt）
varnames = [ ...
    arrayfun(@(n)sprintf('ENS5DAY%d',  n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENSDAY%d',   n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS6H%02d',  n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS3H%02d',  n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS1H%02d',  n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS5DAYT%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS1DAYT%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS6HT%d',   n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS3HT%d',   n), 1:20, 'uni', 0)  ...
    arrayfun(@(n)sprintf('ENS5DAYU%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS1DAYU%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS6HU%d',   n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS3HU%d',   n), 1:20, 'uni', 0)  ...
    arrayfun(@(n)sprintf('ENS5DAYV%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS1DAYV%d', n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS6HV%d',   n), 1:20, 'uni', 0), ...
    arrayfun(@(n)sprintf('ENS3HV%d',   n), 1:20, 'uni', 0)  ...
];

%% 逐个复制变量
% ② 循环复制数据
for k = 1:numel(varnames)
    vname = varnames{k};
    try
        % 目标文件若无该变量，会触发错误并被 catch 捕获
        ncinfo(dstfile, vname);          % 只检测是否存在
        data = ncread(srcfile, vname);   % 读源数据
        ncwrite(dstfile, vname, data);   % 覆盖写入
        fprintf('Copied %s\n', vname);
    catch ME
        fprintf('Skip  %s  (%s)\n', vname, ME.message);
    end
end

disp('>>> 变量数值复制完成。');
end 